name: Python CI/CD

on:
  push:
    branches:
      - main # Run on pushes to the main branch
  pull_request:
    branches:
      - main # Run on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Or windows-latest, macos-latest

    steps:
    - uses: actions/checkout@v4 # Checkout your code

    - name: Set up Python 3.9 # Specify Python version
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        pytest # This command will find and run your tests